version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: 
      interval: daily
  - package-ecosystem: gradle
    directory: /Sprint-Boot-Test
    schedule:
      interval: daily